---
version: "2.0"

services:
  akash:
    image: akhilkumar7947/regen-on-akash:v1.0.0
    env:
      - GENESIS_URL=https://raw.githubusercontent.com/regen-network/mainnet/main/regen-1/genesis.json
      - PEX=1
      - SEEDS=69975e7afdf731a165e40449fcffc75167a084fc@104.131.169.70:26656
      - PEERS=69975e7afdf731a165e40449fcffc75167a084fc@104.131.169.70:26656
      - PRIVATE_PEER_IDS=8ff88ddff8320066ed57a165846c1df89650ed67
      - ADDR_BOOK_STRICT=1
      - CLI_NAME=regen
      - STATE_SYNC=0
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 9090
        to:
          - global: true

profiles:
  compute:
    akash:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 32Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        akash: 
          denom: uakt
          amount: 50

deployment:
  akash:
    dcloud:
      profile: akash
      count: 1
